name: Build Mod

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew setupCiWorkspace build
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: Flippi-Mod-Jar
          path: build/libs/Flippi-1.0.0.jar
